CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(320) NOT NULL UNIQUE,
  password TEXT NOT NULL,
  tsc_no VARCHAR(255),
  id_no VARCHAR(50),
  responsibility VARCHAR(100),
  assessment_number VARCHAR(255),
  grade VARCHAR(50),
  subject_combination VARCHAR(100),
  department VARCHAR(100),
  country VARCHAR(100),
  phone VARCHAR(32),
  profile_image TEXT,
  role INTEGER DEFAULT 2,
  city VARCHAR(100),
  zip VARCHAR(40),
  street VARCHAR(255),
  apartment VARCHAR(100),
  is_admin BOOLEAN DEFAULT FALSE,
  email_verified BOOLEAN DEFAULT FALSE,
  email_verify_token TEXT,
  reset_token TEXT,
  reset_token_expires TIMESTAMPTZ,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS grade (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    enrolment INT,
    class_teacher VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS teacher(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    tsc_no VARCHAR(200),
    grade VARCHAR(50),
	subject_combination VARCHAR(100),
    department VARCHAR(100),
	responsibility VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS learners(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    assessment_number VARCHAR(255),
    grade VARCHAR(50),
    pos INT,
    responsibility VARCHAR(255),
    class_teacher VARCHAR(100),
    birth_certificate VARCHAR(255),
    english VARCHAR(50),
    english_pl VARCHAR(100),
    english_points VARCHAR(100),
    english_cat1 VARCHAR(50),
    english_cat2 VARCHAR(50),
    english_main VARCHAR(50),
    cre VARCHAR(50),
    cre_pl VARCHAR(100),
    cre_points VARCHAR(100),
    cre_cat1 VARCHAR(50),
    cre_cat2 VARCHAR(50),
    cre_main VARCHAR(50),
    pre_technical VARCHAR(50),
    pre_technical_pl VARCHAR(100),
    pre_technical_points VARCHAR(100),
    pre_technical_cat1 VARCHAR(50),
    pre_technical_cat2 VARCHAR(50),
    pre_technical_main VARCHAR(50),
    integrated_science VARCHAR(50),
    integrated_science_pl VARCHAR(100),
    integrated_science_points VARCHAR(100),
    integrated_science_cat1 VARCHAR(50),
    integrated_science_cat2 VARCHAR(50),
    integrated_science_main VARCHAR(50),
    agriculture VARCHAR(50),
    agriculture_pl VARCHAR(100),
    agriculture_points VARCHAR(100),
    agriculture_cat1 VARCHAR(50),
    agriculture_cat2 VARCHAR(50),
    agriculture_main VARCHAR(50),
    biology VARCHAR(50),
    biology_pl VARCHAR(100),
    biology_points VARCHAR(100),
    biology_cat1 VARCHAR(50),
    biology_cat2 VARCHAR(50),
    biology_main VARCHAR(50),
    mathematics VARCHAR(50),
    mathematics_pl VARCHAR(100),
    mathematics_points VARCHAR(100),
    mathematics_cat1 VARCHAR(50),
    mathematics_cat2 VARCHAR(50),
    mathematics_main VARCHAR(50),
    kiswahili VARCHAR(50),
    kiswahili_pl VARCHAR(100),
    kiswahili_points VARCHAR(100),
    kiswahili_cat1 VARCHAR(50),
    kiswahili_cat2 VARCHAR(50),
    kiswahili_main VARCHAR(50),
    creative_arts VARCHAR(50),
    creative_arts_pl VARCHAR(100),
    creative_arts_points VARCHAR(100),
    creative_arts_cat1 VARCHAR(50),
    creative_arts_cat2 VARCHAR(50),
    creative_arts_main VARCHAR(50),
    evrg VARCHAR(100),
    evrg_pl VARCHAR(100),
    evrg_points VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS learner_results (
    id SERIAL PRIMARY KEY,
    learner_id INTEGER NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
    term VARCHAR(2) NOT NULL,
    english VARCHAR(50),
    english_pl VARCHAR(100),
    english_points VARCHAR(100),
    english_cat1 VARCHAR(50),
    english_cat2 VARCHAR(50),
    english_main VARCHAR(50),
    kiswahili VARCHAR(50),
    kiswahili_pl VARCHAR(100),
    kiswahili_points VARCHAR(100),
    kiswahili_cat1 VARCHAR(50),
    kiswahili_cat2 VARCHAR(50),
    kiswahili_main VARCHAR(50),
    mathematics VARCHAR(50),
    mathematics_pl VARCHAR(100),
    mathematics_points VARCHAR(100),
    mathematics_cat1 VARCHAR(50),
    mathematics_cat2 VARCHAR(50),
    mathematics_main VARCHAR(50),
    integrated_science VARCHAR(50),
    integrated_science_pl VARCHAR(100),
    integrated_science_points VARCHAR(100),
    integrated_science_cat1 VARCHAR(50),
    integrated_science_cat2 VARCHAR(50),
    integrated_science_main VARCHAR(50),
    agriculture VARCHAR(50),
    agriculture_pl VARCHAR(100),
    agriculture_points VARCHAR(100),
    agriculture_cat1 VARCHAR(50),
    agriculture_cat2 VARCHAR(50),
    agriculture_main VARCHAR(50),
    biology VARCHAR(50),
    biology_pl VARCHAR(100),
    biology_points VARCHAR(100),
    biology_cat1 VARCHAR(50),
    biology_cat2 VARCHAR(50),
    biology_main VARCHAR(50),
    cre VARCHAR(50),
    cre_pl VARCHAR(100),
    cre_points VARCHAR(100),
    cre_cat1 VARCHAR(50),
    cre_cat2 VARCHAR(50),
    cre_main VARCHAR(50),
    pre_technical VARCHAR(50),
    pre_technical_pl VARCHAR(100),
    pre_technical_points VARCHAR(100),
    pre_technical_cat1 VARCHAR(50),
    pre_technical_cat2 VARCHAR(50),
    pre_technical_main VARCHAR(50),
    creative_arts VARCHAR(50),
    creative_arts_pl VARCHAR(100),
    creative_arts_points VARCHAR(100),
    creative_arts_cat1 VARCHAR(50),
    creative_arts_cat2 VARCHAR(50),
    creative_arts_main VARCHAR(50),
    evrg VARCHAR(100),
    evrg_pl VARCHAR(100),
    evrg_points VARCHAR(100),
    UNIQUE (learner_id, term)
);

CREATE TABLE IF NOT EXISTS departments(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    hod VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS managers(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    responsibility VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS homework(
    id SERIAL PRIMARY KEY,
    teacher_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    grade VARCHAR(50) NOT NULL,
    subject VARCHAR(100),
    task_description TEXT,
    document_path VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS homework_submissions(
    id SERIAL PRIMARY KEY,
    homework_id INTEGER NOT NULL REFERENCES homework(id) ON DELETE CASCADE,
    learner_id INTEGER NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
    answer_document_path VARCHAR(255),
    teacher_feedback TEXT,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    feedback_at TIMESTAMPTZ,
    UNIQUE (homework_id, learner_id)
);

